name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  animate_do: ^4.0.1
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  google_fonts: ^5.1.0
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
